// * Action Types
const SET_DROP_LIST = "SET_DROP_LIST";
const SET_APP_LIST = "SET_APP_LIST";
const SET_SELECTION = "SET_SELECTION";
const TAKE_SNAPSHOT = "TAKE_SNAPSHOT";

const TOGGLE_ANIMATION = "TOGGLE_ANIMATION";
const TOGGLE_META_KEY = "TOGGLE_META_KEY";
const TOGGLE_SHIFT_KEY = "TOGGLE_SHIFT_KEY";

export {
  SET_DROP_LIST,
  SET_APP_LIST,
  SET_SELECTION,
  TAKE_SNAPSHOT,
  TOGGLE_ANIMATION,
  TOGGLE_META_KEY,
  TOGGLE_SHIFT_KEY,
};
